[project]
name = "ArkUnpacker"
version = "5.1.0"
description = "Arknights Assets Unpacker"
authors = [
    {name = "Harry Huang", email = "harryhuang2652@qq.com"}
]
license = "BSD-3-Clause"
readme = "README.md"
requires-python = ">=3.10,<3.13"
dependencies = [
    "bson (~=0.5)",
    "flatbuffers (~=25.12)",
    "numpy (~=2.2)",
    "Pillow (~=11.3)",
    "psutil (~=7.2)",
    "pycryptodome (~=3.22)",
    "pydub-ng (~=0.1)",
    "rich (~=15.0)",
    "spine-asset (~=1.1)",
    "UnityPy (~=1.25)",
    "wannacri (~=0.3)"
]

[tool.poetry]
package-mode = false

[[tool.poetry.source]]
name = "PyPI-Tsinghua"
url = "https://pypi.tuna.tsinghua.edu.cn/simple"
priority = "primary"

[tool.poetry.group.dev.dependencies]
toml = "0.10.2"
pyinstaller = "6.20.0"

[tool.build]
build-dir = "$project$/build"
entry = "$project$/Main.py"
icon = "$project$/ArkUnpacker.ico"
add-binary = "$venv$/Lib/site-packages/fmod_toolkit/libfmod:fmod_toolkit/libfmod|$venv$/Lib/site-packages/UnityPy/resources/lzma.tpk:UnityPy/resources"
add-data = "$project$/src/fbs/CN:src/fbs/CN|$venv$/Lib/site-packages/archspec/json:archspec/json"
hidden-import = "flatbuffers"
log-level = "WARN"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
