name: Test

on:
  push:
    branches:
      - '**'

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Print ref
        run: |
          echo "Current ref: ${{  github.ref  }}"
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8.10'

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.8.3

      - name: Install dependencies
        run: |
          poetry install
        shell: bash

      - name: Run test script
        run: |
          poetry run python Test.py
        shell: bash
