name: Test

on:
  push:
    branches:
      - '**'

env:
  PYTHONIOENCODING: "UTF-8"

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8.10"]
        poetry-version: ["1.8.3"]
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Install dependencies
        run: |
          poetry install
      - name: Run test script
        run: |
          poetry run python Test.py
